recipes:
    global:
attributes:
    vagrant_plugins:
        - chef
        - knife-block
        - vagrant-box-updater
        - vagrant-hostmanager
        - vagrant-omnibus
#        - vagrant-berkshelf
